apache/rocketmq-site

_docs/16-rmq-architecture.md
https://issues.apache.org/jira/browse/ROCKETMQ-371
=> Fixing typo

.gitignore, _includes/footer.html
Updated the footer to include the essential ASF links.
This in response to the checks whimsy performs: https://whimsy.apache.org/site/project/rocketmq
After merging the PR the website must be re-generated.
=> Additions to footer to include essential ASF links

_data/navigation.yml, _docs/01-quick-start-guide.md, _docs/10-download-releases.md
rocketmq wetsite upate:
1. quick start, add disk space (4g+) prerequisite
2. update download & release page, remove the release menu items
XX
XXXX
=> quick start and release notes update

_pages/community.md
RIP list has been moved to RocketMQ WIKI, so the information of the website needs to be updated.
community.md
=> [ISSUE #41] Update the detail information of RIP

NOTICE, _docs/01-quick-start-guide.md, _docs/10-download-releases.md, _posts/2019-01-17-release-notes-4.4.0.md, home.md
=> Prepare to release RocketMQ 4.4.0

_docs/08-release-manual.md
=> Polish the release manual page

_pages/community.md, _pages/users.md, _posts/2019-03-13-release-notes-4.5.0.md, home.md
Update Release version to 4.5.0 in website.
add release note 4.5.0
=> Update Release version to 4.5.0 in website.

_posts/2019-03-13-release-notes-4.5.0.md
=> Using SHA512 checksum for release 4.5.0

home.md
Modify the latest version to 4.5.0
modify the file of home.md
=> Modify the latest version to 4.5.0

_pages/community.md
Update the commercial support to community
XXXX
=> Update the Commercial Support to Community

_docs/06-best-practice-pull-request.md, _docs/best-practice-create-pr.md
Make users not submit PR to master branch.
=> Should not submit PR to master

_posts/2019-11-20-release-notes-4.6.0.md
Add 4.6.0 release notes
Add 4.6.0 release notes
=> Add 4.6.0 release notes

_docs/14-rmq-deployment.md
Modify the 'SLVAE' to 'SLAVE' in rmq-deployement file
Modify the 'SLVAE' to 'SLAVE' in rmq-deployement file
=> [ISSUE #1729] Modify the 'SLVAE' to 'SLAVE' in rmq-deployement file

_posts/2020-01-14-release-notes-4.6.1.md
Add 4.6.1 release notes
Add 4.6.1 release notes
=> docs(release note):add 4.6.1 release notes

_posts/2020-01-14-release-notes-4.6.1.md
modify 4.6.1 release notes
modify 4.6.1 release notes
XXXX
=> chore(release note):modify 4.6.1 release notes

_posts/2019-11-11-release-notes-rocketmq-client-cpp-1.2.4.md, _posts/2020-02-13-release-notes-rocketmq-client-cpp-1.2.5.md
close #60 Prepare to release cpp 1.2.5
add 1.2.5 release note
=> Prepare to release cpp 1.2.5

_posts/2020-02-14-release-notes-rocketmq-client-cpp-2.0.0.md
feat(release): prepare to release cpp 2.0.0
=> feat(release): prepare to release cpp 2.0.0

_posts/2020-03-31-release-notes-rocketmq-client-go-2.0.0.md
=> prepare to release go native 2.0.0

_about/01-team.md
- move xujianhai666 from contributor to commiter
=> feat: add new commiter

_docs/25-rmq-transaction-example.md
I find some error in `transaction-example` so I fix it
fix java block
XXXX
=> Fix java code block

_about/01-team.md
=> hdchen user profile update

_about/01-team.md
=> Francisoliverlee user profile update

_about/01-team.md
Update ifplusor profile
XX
XXXX
=> Update ifplusor profile

_docs/01-quick-start-guide.md
=> Add guide how to quick start for windows 10

_docs/01-quick-start-guide.md
The cmd for users to send and receive messages under the Windows environment should be 
".\bin\tools.cmd  org.apache.rocketmq.example.quickstart.Producer" and 
".\bin\tools.cmd  org.apache.rocketmq.example.quickstart.Consumer" 
instead of
".\bin\tool.cmd  org.apache.rocketmq.example.quickstart.Producer" and 
".\bin\tool.cmd  org.apache.rocketmq.example.quickstart.Consumer". 
```
.\bin\tool.cmd  org.apache.rocketmq.example.quickstart.Producer
```
to
```
.\bin\tools.cmd  org.apache.rocketmq.example.quickstart.Producer
```
and
```
.\bin\tool.cmd  org.apache.rocketmq.example.quickstart.Consumer
```
to
```
.\bin\tools.cmd  org.apache.rocketmq.example.quickstart.Consumer
```
XXXX
Follow this checklist to help us incorporate …
=> Fix cmd in quick start guide for Windows

.asf.yaml
As requested with https://lists.apache.org/thread.html/r8d023c0f5afefca7f6ce4e26d02404762bd6234fbe328011e1564249%40%3Cusers.infra.apache.org%3E
=> Use .asf.yaml for publishing

_about/02-contact.md
=> [ISSUE #91] remove issues from mailing list

_about/01-team.md
Update to add the reference to the complete committee information of Apache RocketMQ
To add the reference to the complete committee information of Apache RocketMQ
Add the reference in the team document.
XXXX
=> [ISSUES #94 ]Update 01-team.md to add the reference to the complete committee information of Apache RocketMQ

_posts/2021-09-06-release-notes-5.0.0-PREVIEW.md
=> add 5.0.0-PREVIEW release note

_posts/2021-09-23-release-notes-rocketmq-dashboard-1.0.0.md
Add RocketMQ Dashboard 1.0.0 release note
Add RocketMQ Dashboard 1.0.0 release note
check the release note page via my own repository
=> [ISSUES #99 ] Add RocketMQ Dashboard 1.0.0 release note

_posts/2022-01-18-release-notes-rocketmq-streams-1.0.0-preview.md
=> add rocketmq-streams-1.0.0-preview release note

_docs/15-order-message-example .md
=> fix [fix topic name typo]

_docs/01-quick-start-guide.md, _docs/10-download-releases.md, _docs/18-simple-example.md, _pages/community.md, _pages/users.md, home.md
=> feat(docs) bump up rocketmq version to 4.9.3

_docs/07-frequently-asked-questions.md, _docs/14-rmq-deployment.md
=> fix some spell error，relate to https://github.com/apache/rocketmq/pull/4075

_posts/2022-06-20-release-notes-4.9.4.md
=> [ISSUES #132] add 4.9.4 release note

_posts/2022-06-20-release-notes-4.9.4.md
=> [ISSUES #135] add 4.9.4 release note

_docs/01-quick-start-guide.md, _docs/10-download-releases.md, _docs/18-simple-example.md, _pages/community.md, _pages/users.md, home.md
=> update rmq version to 4.9.4

docs/29how-to-contribute.md
Add how-to-contribute chinese document for new official website
Add how-to-contribute chinese document for new official website
XXXX
=> Add how-to-contribute chinese document for new official website

docs/02quickstart.md
Add quick start chinese document for new official website
Add quick start chinese document for new official website
XXXX
=> Add quick start chinese document for new official website

docs/01-介绍/02quickstart.md
Inform users to get the recommended environment or software. The same section would be added once the English-version Quickstart has been merged.
1. Add prerequisite for 02quickstart.md (CN).
=> Add prerequisite for 02quickstart.md (CN)

_posts/2022-07-25-release-notes-rocketmq-client-go-2.1.1.md
=> Prepare to release rocketmq client go 2.1.1

docs/09-英文/01-Introduction/02quickstart.md
Add the Quickstart guide English version.
1. Add 02quickstart.md English version.
- [] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
=> Add 02quickstart.md (en)

_about/01-team.md
=> Add committer hzh

docs/09-英文/02-Producer/04concept1.md
Add the English-version Core Concept section of Producer.
1. Add 02-Producer/04concept1.md
=> Add 02-Producer/04concept1.md (EN)

docs/09-英文/02-producer/09message5.md
Add the English-version document of "Transactional Message Sending".
1. Add docs/09-英文/02-producer/09message5.md
=> Transactional Message Sending (EN)

docs/09-英文/01-Introduction/08message4.md, docs/09-英文/02-Producer/08message4.md
1. Modify the typo in 08message4.md.
2. Add the English-version Batch Message Sending of Producer.
3. Modify the typo in 07message3.md.
4. Add the English-version Delay Message Sending of Producer.
Modify 02-生产者/08message4.md
Add 02-Producer/08message4.md
Modify 02-生产者/07message3.md
Add 02-Producer/07message3.md
=> Batch Message Sending

docs/09-英文/01-Introduction/03whatis.md
Add Whatis Document(en)
XX
XXXX
=> Add Whatis Document(en)

docs/02-生产者/07message3.md, docs/09-英文/02-Producer/07message3.md
1. Modify the typo in 07message3.md.
2. Add the English-version Delay Message Sending of Producer.
Modify 02-生产者/07message3.md
Add 02-Producer/07message3.md
=> Delay message sending

docs/09-英文/02-Producer/06message2.md
Add the English-version Delay Message Sending of Producer.
Add 02-Producer/06message2.md
=> Sequential message sending

i18n/en/docusaurus-plugin-content-docs/current/03-消费者/11concept2.md
Add English-version documents of Consumer Core Concepts.
Add 11concept2.md to rocketmq-site/i18n/docusaurus-plugin-content-docs/urrent/03-消费者.
=> Consumer Core Concepts (EN)

docusaurus.config.js
=> Fix issue#182: fix broken link

i18n/en/docusaurus-plugin-content-docs/current/01-介绍/03whatis.md, i18n/en/docusaurus-plugin-content-docs/current/02-生产者/05message1.md, i18n/en/docusaurus-plugin-content-docs/current/02-生产者/06message2.md, i18n/en/docusaurus-plugin-content-docs/current/02-生产者/08message4.md, i18n/en/docusaurus-plugin-content-docs/current/02-生产者/09message5.md
=> [ISSUE #186] fix build error for en version of new website

.github/workflows/pre-release.yml
=> [ISSUE #188]try to add pre-release action.

.github/workflows/pre-build.yml, .travis.yml, package.json
=> [ISSUE #189] move ci to github actions

src/pages/version 2.md, src/pages/version.md
The original image: https://raw.githubusercontent.com/apache/rocketmq-clients/master/docs/artwork/unified_apis_and_spec.png
=> Update image for lite sdk

docs/05-最佳实践/16dledger.md
fix some problems in 16dledger.md file
- fix some problems in 16dledger.md file
XXXX
=> Fix rocketmq dledger deploy some problems

.github/workflows/pre-release.yml
=> try to auto release office web site

docs/01-介绍/02quickstart.md
Polish documents for quickstart
- Polish documents for quickstart
XXXX
=> Polish documents for quickstart

docusaurus.config.js, package.json
Redirect the staled links from the old official website to the corresponding links within new one.
1. Add 'plugin-client-redirects' plugin.
=> [ISSUE #213] Redirect staled links to new official website

.github/workflows/pre-build.yml, package.json
=> Change plugin-client-redirects version

docusaurus.config.js
Issue link: #213 
1. Update the redirect link list.
=> Update redirect links

docusaurus.config.js
=> Fix redirect link

.github/workflows/pre-build.yml, package.json
Fix the translation icon problem.
1. Update the version of Docusaurus
=> Fix Incorrect Translation Icon

versioned_docs/version-5.0/05-最佳实践/16dledger.md
close #221 
- Optimize RocketMQ 5.0 16dledger.md file
XXXX
=> [ISSUE #221]Optimize RocketMQ 5.0 16dledger.md file

third-blog/2022-09-09-5.0.0.md
=> add release note for 5.0.0

.travis.yml, package.json
=> Fix Travis CI

versioned_docs/version-5.0/02-快速入门/02quickstart.md, versioned_docs/version-5.0/05-部署运维/15deploy.md
=> [ISSUE #242] update the quickstart and deploy doc for proxy

docs/02-生产者/05message1.md, docs/02-生产者/06message2.md, docs/02-生产者/07message3.md, docs/02-生产者/08message4.md, docs/02-生产者/09message5.md, docs/03-消费者/12push.md, docs/03-消费者/13pull.md, docs/04-部署与运维/17Dashboard.md, docs/04-部署与运维/18Exporter.md, docs/05-最佳实践/16dledger.md, docs/05-最佳实践/17messagetra.md, docs/05-最佳实践/20log.md, docs/06-参数配置/23local.md, docs/08-贡献指南/31pull-request.md
close #223
- Fix document some codes display and document  format problems
XXXX
=> [ISSUE #223]Fix document some codes display and document  format problems

docs/01-介绍/03whatis.md, docusaurus.config.js, i18n/en/docusaurus-plugin-content-docs/current/01-介绍/03whatis.md, src/pages/components/Hero.js, src/pages/download.md, third-blog/2017-01-24-4.0.0.md, third-blog/2017-12-13-4.2.0.md, third-blog/2018-07-24-4.3.0.md, third-blog/2018-08-29-4.3.1.md, third-blog/2018-11-02-4.3.2.md, third-blog/2019-01-17-4.4.0.md, third-blog/2019-03-29-4.5.0.md, third-blog/2019-05-13-4.5.1.md, third-blog/2019-08-02-4.5.2.md, third-blog/2019-11-25-4.6.0.md, third-blog/2020-03-16-4.7.0.md, third-blog/2020-06-29-4.7.1.md, third-blog/2020-12-21-4.8.0.md, third-blog/2020-2-14-4.6.1.md, third-blog/2021-06-15-4.9.0.md, third-blog/2021-08-22-4.9.1.md, third-blog/2021-10-26-4.9.2.md, third-blog/2022-03-04-4.9.3.md, third-blog/2022-03-04-4.9.4.md, third-blog/2022-03-15-5.0.0-ALPHA.md, versioned_docs/version-5.0/02-快速入门/02quickstart.md
refer to #255 and #254 
XX
XXXX
=> #255 add release notes for rocketmq 5, update default version to 5.0

docs/08-贡献指南/32release-manual.md
Polish release manual again
Polish release manual again
XXXX
=> [ISSUE #258] Polish release manual again

i18n/en/docusaurus-plugin-content-docs/current/03-消费者/13pull.md
Add the English-version Pull Consumer
Add i18n/en/docusaurus-plugin-content-docs/current/03-消费者/13pull.md
=>  Pull Consumer

versioned_docs/version-5.0/02-快速入门/02quickstart.md
close #276 
- Fix Rocketmq5.0 quick start document display format problem
XXXX
=> [ISSUE #276]Fix Rocketmq5.0 quick start document display format problem

docs/02-生产者/09message5.md, versioned_docs/version-5.0/02-快速入门/02quickstart.md, versioned_docs/version-5.0/04-功能行为/09consumerprogress.md
=> New official website develop

docs/03-消费者/12push.md, docs/04-部署与运维/18Exporter.md, docs/05-最佳实践/15bestpractice.md, docs/05-最佳实践/18access.md, docs/05-最佳实践/21subscribe.md, i18n/en/docusaurus-plugin-content-docs/current/01-介绍/02quickstart.md, i18n/en/docusaurus-plugin-content-docs/current/02-生产者/05message1.md, i18n/en/docusaurus-plugin-content-docs/current/02-生产者/06message2.md
closes #228 
-  Polish up document command formate
- change some document formate
XXXX
=> [ISSUE #228] Polish up document command formate

i18n/en/code.json, src/pages/components/Hero.js
Modify the content of the home page.
1. Modify the code in Hero.js & code.json
XXXX
=> Modify Home Page Content

.asf.yaml
close #309 add labels to repo description
add labels to repo description
XXXX
=> [ISSUE #309] add labels to repo description.
